name: Publish

on: push

jobs:
  build-java:
    uses: CoffeeCoder1/VendorTools/.github/workflows/build-java.yml@3a85fa237c23f822b9931fc8cdcbbfa6385dd970

  update-maven:
    needs: [build-java]
    runs-on: ubuntu-latest

    # Only deploy on tag
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Generate an authentication token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.BLAZER_BOT_APP_ID }}
          private-key: ${{ secrets.BLAZER_BOT_PRIVATE_KEY }}
          # Set the owner, so the token can be used in all repositories
          owner: ${{ github.repository_owner }}

      - name: Trigger update
        uses: CoffeeCoder1/VendorTools/.github/actions/trigger-maven-update
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          repository-name: roboblazers7617/maven-repo
          maven-name: limelight
